name: Build Documentation with MkDocs
on:
  push:
    branches:
      - main

env:
  ClassPP_Version: '2.0'
  Deploy_Type: 'release'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      
      - name: Install necessary tools
        run: | 
          pip install mkdocs-material
          pip install pillow cairosvg
          pip install --upgrade setuptools
          pip install mike

      - name: Configure the git user
        run: |
          git config user.name classppdoc
          git config user.email classppdoc@example.com

      - name: Fetch the gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Deploy latest documentation version and set to latest
        if: env.Deploy_Type == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mike deploy $ClassPP_Version latest --update-aliases --branch gh-pages
          mike set-default --push latest --branch gh-pages 

      - name: Deploy indev documentation
        if: env.Deploy_Type == 'indev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mike deploy $ClassPP_Version --push --update-aliases --branch gh-pages 